import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import About from "@/components/About/About";
import Nav from "@/components/Nav/Nav";
import appConfig from "@/app.config";
import Articles from "@/components/Articles/Articles";
import Projects from "@/components/Projects/Projects";
import Presentations from "@/components/Presentation/Presentations";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Nav links={appConfig.links} />
        <About name={appConfig.about.name}
          img={appConfig.about.img}
          description={appConfig.about.description}
          socialLinks={appConfig.about.socialLinks}
          title={appConfig.about.title} />

        <Articles articles={appConfig.articles} />
        <Projects projects={appConfig.projects} />
        <Presentations presentations={appConfig.presentations} />
        <Footer links={appConfig.links} author={appConfig.about.name} />
      </main>
    </>
  );
}
